version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=mystrongpassword  # Set the same password here
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: db-1
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mystrongpassword  # Provide the password directly
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
